theme: minima
title: Welcome to my blog!
author: Dev Shinde
email: devshinde522@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 

# social links
twitter_username: DevVijayShinde1!
github_username:  im_devshinde
show_excerpts: true # set to false to remove excerpts on the homepage
